import { Noto_Sans_KR } from "next/font/google";
import type { Metadata } from "next";
import "./globals.css";
import { twMerge } from "tailwind-merge";
import { CustomThemeProvider } from "@/components/custom-theme-provider";
import { TooltipProvider } from "@/components/ui/tooltip";

const notoSansKR = Noto_Sans_KR({
  subsets: ["latin"],
  variable: "--font-noto-sans-kr",
  weight: ["400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko" suppressHydrationWarning>
      <body className={twMerge(notoSansKR.className)}>
        <CustomThemeProvider>
          <TooltipProvider>{children}</TooltipProvider>
        </CustomThemeProvider>
      </body>
    </html>
  );
}
